name: test
on: workflow_dispatch
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
     - name: get env
       uses:  actions/setup-node@v4.0.2
     - name: install dependices
       run: npm ci
     - name: run tests
       run: npm run lint
     - name: run test
       run: npm run test
     - name: run build
       run: npm run build
      
  
